### ISSUE TITLE
Bug when validating schema with "multipleOf" field

### ISSUE THREAD

**Issue by slinkydeveloper** [RepreZen/KaiZen-OpenApi-Parser#44]
# Bug in NumericUtils.NumericType

## Description
When you try to load a path parameter (I think in general a scheme) with "multipleOf" field, it fails in a `ExceptionInInitializerError` inside `NumericUtils.zero()`

## Steps to reproduce
Try to load and validate a spec with a path like this:
```yaml
/pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: integer
            multipleOf: 1.0
```
