### ISSUE TITLE
openIdConnectUrl is required with apiKey security schema type

### ISSUE THREAD

**Issue by slinkydeveloper** [RepreZen/KaiZen-OpenApi-Parser#50]
Why "`openIdConnectUrl` is required" is thrown when security schema type is `apiKey`? It seems useless with an api key security. It throw the same error with `basic` security type. For example:
```yaml
api_key:
    type: apiKey
    name: api_key
    in: header
    openIdConnectUrl: "http://www.example.com"
```
